### ISSUE TITLE
transfer

### ISSUE THREAD

**Issue by kaelkael1737** [greymass/anchor-link#39]
Hello,
I discover eosio and everything that goes with it.
I just did a test with anchor-link to connect, and to transfer eos, and everything works.
Is it possible to transfer or stake nfts in the same way?

**Comment by aaroncox** [comment]
Yep, any type of transaction will work with this same approach.

I'm closing this issue out since this is more of a discussion, and most likely we'll lose track of the discussion pretty quick. If you'd like to discuss what's possible with other developers, I'd recommend either the Telegram or Discord communities:

https://t.me/antelopedevs

https://discord.gg/eos-network
